// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbqVl8A5JfblcGCPo4pccL2-wzvMa_M3s',
    appId: '1:352667610898:web:81be2f4c06976b6ac28dcb',
    messagingSenderId: '352667610898',
    projectId: 'utubemusic-85e2c',
    authDomain: 'utubemusic-85e2c.firebaseapp.com',
    storageBucket: 'utubemusic-85e2c.appspot.com',
    measurementId: 'G-DQ2CFMJXLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR3nbJdggXe7DUdC199Bakuf0d3kQu-i8',
    appId: '1:352667610898:android:ee054f54214444d5c28dcb',
    messagingSenderId: '352667610898',
    projectId: 'utubemusic-85e2c',
    storageBucket: 'utubemusic-85e2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg5XT0oVr5E8mcYn2OrgprOhx2vgbY9QU',
    appId: '1:352667610898:ios:a30396433f690247c28dcb',
    messagingSenderId: '352667610898',
    projectId: 'utubemusic-85e2c',
    storageBucket: 'utubemusic-85e2c.appspot.com',
    iosBundleId: 'com.example.youtubeMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg5XT0oVr5E8mcYn2OrgprOhx2vgbY9QU',
    appId: '1:352667610898:ios:c309fb6110c6f8e0c28dcb',
    messagingSenderId: '352667610898',
    projectId: 'utubemusic-85e2c',
    storageBucket: 'utubemusic-85e2c.appspot.com',
    iosBundleId: 'com.example.youtubeMusic.RunnerTests',
  );
}
